### ISSUE TITLE
Capstone-JS Setup Review

### ISSUE THREAD

**Issue by rebel216** [rebel216/Capstone_Javascript#21]
https://github.com/rebel216/Capstone_Javascript/projects/1

Number of coders is 2 .

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @rebel216 , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] The project requires that you chose who will be Student A and Student B and you need to assign each one of the students to the correct card. Kindly assign the students to the cards. Remember that all cards must have someone assigned, even the group task cards.
-
<img width="361" alt="image" src="https://user-images.githubusercontent.com/61919617/187466005-7e9ec4bf-0ac8-49d3-8b0b-970e139d84b6.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @rebel216, and @AlucardSanin 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] As requested by the previous reviewer, Please assign team members to all task cards even for group task cards. Please assign team members to the following cards.
![image](https://user-images.githubusercontent.com/83803414/187509223-1e43671f-be4f-4900-83b2-5b9371d33e7a.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sumairq** [comment]
### Hi Team 

<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
